name: Deploy Svelte Site to GitHub Pages

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install

      - name: Build the Site
        run: pnpm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0
        with:
             # Optional static site generator to attempt to configure: "nuxt", "next", "gatsby", or "sveltekit"
             static_site_generator: sveltekit
             # Optional file path to static site generator configuration file
             
             # GitHub token
             token: ${{ github.token }}
             # Try to enable Pages for the repository if it is not already enabled. This option requires a token other than `GITHUB_TOKEN` to be provided. In the context of a Personal Access Token, the `repo` scope or Pages write permission is required. In the context of a GitHub App, the `administration:write` and `pages:write` permissions are required.
             enablement: true
          
